"""`chatnec init` scaffolds a new agent project: an env file, a starter app.py
wired up with create_app(), and a README with next steps — so getting a bot
running is copy-paste-run rather than assembling it from the library docs.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

APP_TEMPLATE = '''"""Generated by `chatnec init`. Any callable becomes a bot on every platform
you've configured in .env — swap `my_agent` for your own framework's call.

Run:
    uvicorn app:app --reload
"""
from chatnec import create_app
from chatnec.integrations import from_function


def my_agent(text: str, context: dict) -> str:
    turn = context.get("turn", 0) + 1
    context["turn"] = turn
    return f"(turn {turn}) You said: {text}"


app = create_app(handler=from_function(my_agent))
'''

ENV_TEMPLATE = """# Fill in credentials for the platforms you're using — an unset platform is
# simply inactive. See https://github.com/Nivesh30/chatnec for setup notes.

# SLACK_SIGNING_SECRET is required, not optional — without it /webhook/slack
# rejects every request.
SLACK_BOT_TOKEN=
SLACK_SIGNING_SECRET=

TELEGRAM_BOT_TOKEN=

TEAMS_APP_ID=
TEAMS_APP_PASSWORD=

# WHATSAPP_APP_SECRET is required, not optional — without it /webhook/whatsapp
# rejects every request.
WHATSAPP_ACCESS_TOKEN=
WHATSAPP_PHONE_NUMBER_ID=
WHATSAPP_APP_SECRET=
WHATSAPP_VERIFY_TOKEN=

DISCORD_BOT_TOKEN=

REDIS_URL=

# Required to use POST /reply (async agent replies) — the endpoint refuses all
# requests until this is set, and then requires it as the X-API-Key header.
REPLY_API_KEY=
"""

README_TEMPLATE = """# {name}

A chatnec agent project.

## Run locally

```bash
pip install chatnec
uvicorn app:app --reload
```

Then point whichever platform's webhook you're using at
`https://<your-host>/webhook/<platform>` (`slack`, `telegram`, `teams`, or
`whatsapp`; Discord doesn't need a webhook URL — it connects itself once
`DISCORD_BOT_TOKEN` is set).

Edit `my_agent` in `app.py` to call your actual agent/framework instead of echoing.
"""

GITIGNORE_TEMPLATE = """.env
__pycache__/
*.pyc
.venv/
"""


def init_project(directory: Path) -> None:
    directory.mkdir(parents=True, exist_ok=True)

    name = directory.resolve().name
    files = {
        "app.py": APP_TEMPLATE,
        ".env.example": ENV_TEMPLATE,
        "README.md": README_TEMPLATE.format(name=name),
        ".gitignore": GITIGNORE_TEMPLATE,
    }

    for filename, content in files.items():
        path = directory / filename
        if path.exists():
            print(f"skip  {filename} (already exists)")
            continue
        path.write_text(content, encoding="utf-8")
        print(f"write {filename}")

    print(f"\nDone. Next steps:\n  cd {directory}\n  cp .env.example .env  # fill in credentials\n  pip install chatnec\n  uvicorn app:app --reload")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="chatnec")
    subparsers = parser.add_subparsers(dest="command", required=True)

    init_parser = subparsers.add_parser("init", help="Scaffold a new chatnec agent project")
    init_parser.add_argument("directory", nargs="?", default=".", help="Target directory (default: current directory)")

    args = parser.parse_args(argv)

    if args.command == "init":
        init_project(Path(args.directory))
        return 0

    return 1


if __name__ == "__main__":
    sys.exit(main())
